name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Swift
        uses: actions/setup-swift@v2.2.2

      - name: Build
        run: swift build
